kind: pipeline
name: default

steps:
  - name: build
    image: node:10
    commands:
      - yarn
      - yarn test
      - yarn typecheck
      - yarn lint
    when:
      branch:
        - develop

---
kind: pipeline
type: docker
name: tag

steps:
  - name: tag
    image: docker:git
    commands:
      - ./pipeline.sh
      - git tag $(<.tags)
      - git push origin $(<.tags)
    when:
      branch:
        - develop
      event:
        exclude:
          - pull_request
          - tag

---
kind: pipeline
type: docker
name: publish

steps:
  - name: build
    image: node:10
    commands:
      - echo -n ${DRONE_TAG} > .tags

  - name: docker
    image: plugins/docker
    settings:
      repo: drill4j/admin-ui
      username:
        from_secret: drill_username
      password:
        from_secret: drill_password
      build_args:
        - ENV=development

trigger:
  event:
    - tag
