version: '3'
services:
  admin-ui:
    build:
      args:
        ENV: development
    networks:
      - drill4j-dev-network
    ports:
      - 8080:8080
networks:
  drill4j-dev-network:
    external:
      name: drill4j-dev-network
