import * as React from 'react';
import { BEM } from '@redneckz/react-bem-helper';

import { Icons } from '../../../../../../components';

import styles from './build-version-name.module.scss';

interface Props {
  className?: string;
  newBuild?: any;
}

const buildVersionName = BEM(styles);

export const BuildVersionName = buildVersionName(({ className, newBuild: { current } }: Props) => {
  const [isEdit, setEdit] = React.useState(true);
  return (
    <div className={className}>
      <Title>Build version name</Title>
      <Content>
        {isEdit ? (
          <>
            <VersionName>{`${current.id} (autogenerated)`}</VersionName>
            <IconsWrapper onClick={() => setEdit(!isEdit)}>
              <Icons.Edit />
            </IconsWrapper>
          </>
        ) : (
          <>
            <Content>
              <IconsWrapper type="save">
                <Icons.Checkbox width={16} height={16} /> <Text>Save</Text>
              </IconsWrapper>
              <IconsWrapper type="cancel" onClick={() => setEdit(!isEdit)}>
                <Icons.Close width={16} height={16} /> <Text>Cancel</Text>
              </IconsWrapper>
            </Content>
          </>
        )}
      </Content>
    </div>
  );
});

const Title = buildVersionName.title('div');
const IconsWrapper = buildVersionName.iconsWrapper('div');
const Content = buildVersionName.content('div');
const VersionName = buildVersionName.versionName('span');
const Text = buildVersionName.text('span');
const FormSize = buildVersionName.formSize('div');
